# This will concatenate the javascript files specified in :files to public/js/all.js
guard :concatfilter, type: "js", files: %w(), input_dir: "public/js", output: "public/js/all"

guard :concatfilter, type: "css", files: %w(), input_dir: "public/css", output: "public/css/all"
